In [1]:
import torch
from torch.nn import Linear, ReLU, Sequential, Softmax

In [31]:
X = torch.tensor([[5, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=torch.float32)
model = Sequential(
    Linear(3, 4),
    ReLU(),
    Linear(4, 2),
    ReLU(),
    Linear(2, 1),
)
print(model(X))

tensor([[0.6633],
        [1.1988],
        [1.5079],
        [1.8171]], grad_fn=<AddmmBackward0>)


In [38]:
X = torch.tensor([[5, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=torch.float32)
model = Sequential(
    Linear(3, 16),
    ReLU(),
    Linear(16, 32),
    ReLU(),
    Linear(32, 5),
    Softmax(),
)
print(model(X))

tensor([[0.0920, 0.2258, 0.3327, 0.1334, 0.2161],
        [0.1099, 0.1091, 0.4412, 0.1069, 0.2329],
        [0.0674, 0.0584, 0.6323, 0.0520, 0.1899],
        [0.0357, 0.0280, 0.7763, 0.0221, 0.1379]], grad_fn=<SoftmaxBackward0>)


In [39]:
X = torch.tensor([[5, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=torch.float32)
model = Sequential(
    Linear(3, 32),
    ReLU(),
    Linear(32, 32),
    ReLU(),
    Linear(32, 1),
)
print(model(X))

tensor([[ 0.1170],
        [ 0.1064],
        [ 0.0210],
        [-0.0669]], grad_fn=<AddmmBackward0>)


In [40]:
X = torch.tensor([[5, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=torch.float32)
model = Sequential(
    Linear(3, 16),
    ReLU(),
    Linear(16, 1),
    Sigmoid(),
)
print(model(X))

tensor([[0.1843],
        [0.2168],
        [0.1279],
        [0.0714]], grad_fn=<SigmoidBackward0>)


In [1]:
import torch
from torch.nn import MSELoss, Linear, ReLU, Sequential, Softmax, Sigmoid, CrossEntropyLoss, BCELoss

In [8]:
loss_fn = CrossEntropyLoss()
# Example of using CrossEntropyLoss
y = torch.tensor([0, 1, 0, 1], dtype=torch.long)  # True labels
y_hat = torch.tensor([[0.2, 0.8], [0.6, 0.4], [0.1, 0.9], [0.7, 0.3]], dtype=torch.float32)  # Predicted probabilities
print(loss_fn(y_hat, y))

tensor(0.9799)


In [22]:
y = torch.tensor([ 1, 2, 0])  # True labels
y_hat = torch.tensor([[0.2], [-0.6], [0.1], [0.7], [0.5], [0.9], [0.6], [0.3], [0.1]])  # Predicted probabilities
score = (y_hat.argmax(1) == y).sum() / len(y) * 100
print(score)

RuntimeError: The size of tensor a (9) must match the size of tensor b (3) at non-singleton dimension 0